### ISSUE TITLE
React Native 0.62 Flipper support

### ISSUE THREAD

**Issue by lukebars** [infinitered/flipper-plugin-reactotron#30]
Hi, does it support RN 0.62 with flipper? I've added the plugin but it doesn't show up anywhere

**Comment by lukebars** [comment]
@rmevans9 Any steps to start?

**Comment by rmevans9** [comment]
Hey @lukebars sorry for the late reply! I am actually working on the documentation updates now. Been taking a bit longer then I was hoping due to other obligations but I can give you a quick rundown here.

First make sure you configure your app for use with Reactotron: https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md

After that you just need to make the change listed in the Breaking Changes here: https://github.com/infinitered/reactotron-react-native/releases/tag/v5.0.0

After that you should see the reactotron plugin show in flipper after you reload your app.

**Comment by lukebars** [comment]
Thanks @rmevans9 ! Worked like a charm :shipit:

**Comment by rmevans9** [comment]
Excellent! I will hopefully have the documentation updates complete soon which will help avoid this confusion in the future.

**Comment by alexstanbury** [comment]
Is it really necessary to install `react-native-flipper` for a project that was bootstrapped at version 62+ which already includes flipper by default? I ask because I am getting build errors after installing it and then later building for release, and it seems like it should not be needed if it's already included.

**Comment by mweststrate** [comment]
@alexstanbury is the error on iOS? In that case `react-native-flipper@0.44.0-fix-976-2` should fix the issue (see https://github.com/facebook/flipper/issues/976). 

And yes, that package is needed, as without it Flipper can't be used from JavaScript.

**Comment by ravi-poonia** [comment]
I did all the above steps and i'm getting the log "Reactotron Configured" as well but it's still not coming up in Flipper.
RN version : 0.63.2
 "react-native-flipper": "^0.60.0",
 "reactotron-react-native": "^5.0.0",

**Comment by JanithaR** [comment]
> Hey @lukebars sorry for the late reply! I am actually working on the documentation updates now. Been taking a bit longer then I was hoping due to other obligations but I can give you a quick rundown here.
> 
> First make sure you configure your app for use with Reactotron: https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md
> 
> After that you just need to make the change listed in the Breaking Changes here: https://github.com/infinitered/reactotron-react-native/releases/tag/v5.0.0
> 
> Also call `yarn add react-native-flipper` and then rebuild your app
> 
> After that you should see the reactotron plugin show in flipper after you reload your app.

This is a lot of crucial information that is required to use this plugin. I'm surprised the README is still in an empty state.
